version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    env_file: ".env"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  db:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
